# POST http://localhost:8081/login HTTP/1.1
# content-type: application/json

# {
#     "email": "test@test.com",
#     "password": "12345678"
# }
 PUT http://localhost:8081/songs/3 HTTP/1.1
 Content-Type: application/json

  {
      "title": "Crazy",
      "artist": "Gnarls Barkley",
      "genre": "Neo sul, Pop, Hip Hop, R&B",
      "album": "St. Elsewhere",
      "albumImageUrl": "DataTypes",
      "youtubeId": "N4jf6rtyuw",   
      "lyrics": "",
      "tab": ""
  }

 GET http://localhost:8081/songs HTTP/1.1
